// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using Uroskur.Shared.Models;
//
//    var yrForecast = YrForecast.FromJson(jsonString);

namespace Uroskur.Models.Yr;

public partial class YrData
{
    [JsonProperty("type", NullValueHandling = NullValueHandling.Ignore)]
    public string Type { get; set; }

    [JsonProperty("geometry", NullValueHandling = NullValueHandling.Ignore)]
    public Geometry Geometry { get; set; }

    [JsonProperty("properties", NullValueHandling = NullValueHandling.Ignore)]
    public Properties Properties { get; set; }
}

public partial class Geometry
{
    [JsonProperty("type", NullValueHandling = NullValueHandling.Ignore)]
    public string Type { get; set; }

    [JsonProperty("coordinates", NullValueHandling = NullValueHandling.Ignore)]
    public List<double> Coordinates { get; set; }
}

public partial class Properties
{
    [JsonProperty("meta", NullValueHandling = NullValueHandling.Ignore)]
    public Meta Meta { get; set; }

    [JsonProperty("timeseries", NullValueHandling = NullValueHandling.Ignore)]
    public List<Timesery> Timeseries { get; set; }
}

public partial class Meta
{
    [JsonProperty("updated_at", NullValueHandling = NullValueHandling.Ignore)]
    public DateTimeOffset? UpdatedAt { get; set; }

    [JsonProperty("units", NullValueHandling = NullValueHandling.Ignore)]
    public Units Units { get; set; }
}

public partial class Units
{
    [JsonProperty("air_pressure_at_sea_level", NullValueHandling = NullValueHandling.Ignore)]
    public string AirPressureAtSeaLevel { get; set; }

    [JsonProperty("air_temperature", NullValueHandling = NullValueHandling.Ignore)]
    public string AirTemperature { get; set; }

    [JsonProperty("air_temperature_max", NullValueHandling = NullValueHandling.Ignore)]
    public string AirTemperatureMax { get; set; }

    [JsonProperty("air_temperature_min", NullValueHandling = NullValueHandling.Ignore)]
    public string AirTemperatureMin { get; set; }

    [JsonProperty("air_temperature_percentile_10", NullValueHandling = NullValueHandling.Ignore)]
    public string AirTemperaturePercentile10 { get; set; }

    [JsonProperty("air_temperature_percentile_90", NullValueHandling = NullValueHandling.Ignore)]
    public string AirTemperaturePercentile90 { get; set; }

    [JsonProperty("cloud_area_fraction", NullValueHandling = NullValueHandling.Ignore)]
    public string CloudAreaFraction { get; set; }

    [JsonProperty("cloud_area_fraction_high", NullValueHandling = NullValueHandling.Ignore)]
    public string CloudAreaFractionHigh { get; set; }

    [JsonProperty("cloud_area_fraction_low", NullValueHandling = NullValueHandling.Ignore)]
    public string CloudAreaFractionLow { get; set; }

    [JsonProperty("cloud_area_fraction_medium", NullValueHandling = NullValueHandling.Ignore)]
    public string CloudAreaFractionMedium { get; set; }

    [JsonProperty("dew_point_temperature", NullValueHandling = NullValueHandling.Ignore)]
    public string DewPointTemperature { get; set; }

    [JsonProperty("fog_area_fraction", NullValueHandling = NullValueHandling.Ignore)]
    public string FogAreaFraction { get; set; }

    [JsonProperty("precipitation_amount", NullValueHandling = NullValueHandling.Ignore)]
    public string PrecipitationAmount { get; set; }

    [JsonProperty("precipitation_amount_max", NullValueHandling = NullValueHandling.Ignore)]
    public string PrecipitationAmountMax { get; set; }

    [JsonProperty("precipitation_amount_min", NullValueHandling = NullValueHandling.Ignore)]
    public string PrecipitationAmountMin { get; set; }

    [JsonProperty("probability_of_precipitation", NullValueHandling = NullValueHandling.Ignore)]
    public string ProbabilityOfPrecipitation { get; set; }

    [JsonProperty("probability_of_thunder", NullValueHandling = NullValueHandling.Ignore)]
    public string ProbabilityOfThunder { get; set; }

    [JsonProperty("relative_humidity", NullValueHandling = NullValueHandling.Ignore)]
    public string RelativeHumidity { get; set; }

    [JsonProperty("ultraviolet_index_clear_sky", NullValueHandling = NullValueHandling.Ignore)]
    [JsonConverter(typeof(ParseStringConverter))]
    public long? UltravioletIndexClearSky { get; set; }

    [JsonProperty("wind_from_direction", NullValueHandling = NullValueHandling.Ignore)]
    public string WindFromDirection { get; set; }

    [JsonProperty("wind_speed", NullValueHandling = NullValueHandling.Ignore)]
    public string WindSpeed { get; set; }

    [JsonProperty("wind_speed_of_gust", NullValueHandling = NullValueHandling.Ignore)]
    public string WindSpeedOfGust { get; set; }

    [JsonProperty("wind_speed_percentile_10", NullValueHandling = NullValueHandling.Ignore)]
    public string WindSpeedPercentile10 { get; set; }

    [JsonProperty("wind_speed_percentile_90", NullValueHandling = NullValueHandling.Ignore)]
    public string WindSpeedPercentile90 { get; set; }
}

public partial class Timesery
{
    [JsonProperty("time", NullValueHandling = NullValueHandling.Ignore)]
    public DateTimeOffset Time { get; set; }

    [JsonProperty("data", NullValueHandling = NullValueHandling.Ignore)]
    public Data Data { get; set; }
}

public partial class Data
{
    [JsonProperty("instant", NullValueHandling = NullValueHandling.Ignore)]
    public Instant Instant { get; set; }

    [JsonProperty("next_12_hours", NullValueHandling = NullValueHandling.Ignore)]
    public Next12_Hours Next12_Hours { get; set; }

    [JsonProperty("next_1_hours", NullValueHandling = NullValueHandling.Ignore)]
    public Next1_Hours Next1_Hours { get; set; }

    [JsonProperty("next_6_hours", NullValueHandling = NullValueHandling.Ignore)]
    public Next6_Hours Next6_Hours { get; set; }
}

public partial class Instant
{
    [JsonProperty("details", NullValueHandling = NullValueHandling.Ignore)]
    public Dictionary<string, double> Details { get; set; }
}

public partial class Next12_Hours
{
    [JsonProperty("summary", NullValueHandling = NullValueHandling.Ignore)]
    public Next12_HoursSummary Summary { get; set; }

    [JsonProperty("details", NullValueHandling = NullValueHandling.Ignore)]
    public Next12_HoursDetails Details { get; set; }
}

public partial class Next12_HoursDetails
{
    [JsonProperty("probability_of_precipitation", NullValueHandling = NullValueHandling.Ignore)]
    public double? ProbabilityOfPrecipitation { get; set; }
}

public partial class Next12_HoursSummary
{
    [JsonProperty("symbol_code", NullValueHandling = NullValueHandling.Ignore)]
    public string SymbolCode { get; set; }

    [JsonProperty("symbol_confidence", NullValueHandling = NullValueHandling.Ignore)]
    public string SymbolConfidence { get; set; }
}

public partial class Next1_Hours
{
    [JsonProperty("summary", NullValueHandling = NullValueHandling.Ignore)]
    public Next1_HoursSummary Summary { get; set; }

    [JsonProperty("details", NullValueHandling = NullValueHandling.Ignore)]
    public Next1_HoursDetails Details { get; set; }
}

public partial class Next1_HoursDetails
{
    [JsonProperty("precipitation_amount", NullValueHandling = NullValueHandling.Ignore)]
    public double PrecipitationAmount { get; set; }

    [JsonProperty("precipitation_amount_max", NullValueHandling = NullValueHandling.Ignore)]
    public double PrecipitationAmountMax { get; set; }

    [JsonProperty("precipitation_amount_min", NullValueHandling = NullValueHandling.Ignore)]
    public double PrecipitationAmountMin { get; set; }

    [JsonProperty("probability_of_precipitation", NullValueHandling = NullValueHandling.Ignore)]
    public double ProbabilityOfPrecipitation { get; set; }

    [JsonProperty("probability_of_thunder", NullValueHandling = NullValueHandling.Ignore)]
    public double ProbabilityOfThunder { get; set; }
}

public partial class Next1_HoursSummary
{
    [JsonProperty("symbol_code", NullValueHandling = NullValueHandling.Ignore)]
    public string SymbolCode { get; set; }
}

public partial class Next6_Hours
{
    [JsonProperty("summary", NullValueHandling = NullValueHandling.Ignore)]
    public Next1_HoursSummary Summary { get; set; }

    [JsonProperty("details", NullValueHandling = NullValueHandling.Ignore)]
    public Next6_HoursDetails Details { get; set; }
}

public partial class Next6_HoursDetails
{
    [JsonProperty("air_temperature_max", NullValueHandling = NullValueHandling.Ignore)]
    public double AirTemperatureMax { get; set; }

    [JsonProperty("air_temperature_min", NullValueHandling = NullValueHandling.Ignore)]
    public double AirTemperatureMin { get; set; }

    [JsonProperty("precipitation_amount", NullValueHandling = NullValueHandling.Ignore)]
    public double PrecipitationAmount { get; set; }

    [JsonProperty("precipitation_amount_max", NullValueHandling = NullValueHandling.Ignore)]
    public double PrecipitationAmountMax { get; set; }

    [JsonProperty("precipitation_amount_min", NullValueHandling = NullValueHandling.Ignore)]
    public double PrecipitationAmountMin { get; set; }

    [JsonProperty("probability_of_precipitation", NullValueHandling = NullValueHandling.Ignore)]
    public double ProbabilityOfPrecipitation { get; set; }
}

public partial class YrData
{
    public static YrData FromJson(string json) => JsonConvert.DeserializeObject<YrData>(json, Converter.Settings);
}

public static class Serialize
{
    public static string ToJson(this YrData self) => JsonConvert.SerializeObject(self, Converter.Settings);
}

internal static class Converter
{
    public static readonly JsonSerializerSettings Settings = new JsonSerializerSettings
    {
        MetadataPropertyHandling = MetadataPropertyHandling.Ignore,
        DateParseHandling = DateParseHandling.None,
        Converters =
            {
                new IsoDateTimeConverter { DateTimeStyles = DateTimeStyles.AssumeUniversal }
            },
    };
}

internal class ParseStringConverter : JsonConverter
{
    public override bool CanConvert(Type t) => t == typeof(long) || t == typeof(long?);

    public override object ReadJson(JsonReader reader, Type t, object existingValue, JsonSerializer serializer)
    {
        if (reader.TokenType == JsonToken.Null) return null;
        var value = serializer.Deserialize<string>(reader);
        long l;
        if (Int64.TryParse(value, out l))
        {
            return l;
        }
        throw new Exception("Cannot unmarshal type long");
    }

    public override void WriteJson(JsonWriter writer, object untypedValue, JsonSerializer serializer)
    {
        if (untypedValue == null)
        {
            serializer.Serialize(writer, null);
            return;
        }
        var value = (long)untypedValue;
        serializer.Serialize(writer, value.ToString());
        return;
    }

    public static readonly ParseStringConverter Singleton = new ParseStringConverter();
}
