// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using Uroskur.Models.Yr;
//
//    var yrSunriseData = YrSunriseData.FromJson(jsonString);

namespace Uroskur.Models.Yr
{
    using System;
    using Newtonsoft.Json;

    public partial class YrSunriseData
    {
        [JsonProperty("copyright")]
        public string Copyright { get; set; }

        [JsonProperty("licenseURL")]
        public Uri LicenseUrl { get; set; }

        [JsonProperty("type")]
        public string Type { get; set; }

        [JsonProperty("geometry")]
        public Geometry Geometry { get; set; }

        [JsonProperty("when")]
        public When When { get; set; }

        [JsonProperty("properties")]
        public Properties Properties { get; set; }
    }

    public partial class Properties
    {
        [JsonProperty("body")]
        public string Body { get; set; }

        [JsonProperty("sunrise")]
        public Sun Sunrise { get; set; }

        [JsonProperty("sunset")]
        public Sun Sunset { get; set; }

        [JsonProperty("solarnoon")]
        public Solar Solarnoon { get; set; }

        [JsonProperty("solarmidnight")]
        public Solar Solarmidnight { get; set; }
    }

    public partial class Solar
    {
        [JsonProperty("time")]
        public string Time { get; set; }

        [JsonProperty("disc_centre_elevation")]
        public double DiscCentreElevation { get; set; }

        [JsonProperty("visible")]
        public bool Visible { get; set; }
    }

    public partial class Sun
    {
        [JsonProperty("time")]
        public string Time { get; set; }

        [JsonProperty("azimuth")]
        public double Azimuth { get; set; }
    }

    public partial class When
    {
        [JsonProperty("interval")]
        public DateTimeOffset[] Interval { get; set; }
    }

    public partial class YrSunriseData
    {
        public static YrSunriseData FromJson(string json) => JsonConvert.DeserializeObject<YrSunriseData>(json, Uroskur.Models.Yr.Converter.Settings);
    }
}
